dashing:
  image: georgeyord/dashing
  ports:
   - 3030:3030
  environment:
   # DASHING OPTIONS
   # To install custom widgets supply the gist IDs of the widgets
  #  - WIDGETS=5641535
   # To install gems, supply the gem name(s) as an environment variable
   # Multiple gems and widgets can be supplied divided by spaces
  #  - GEMS="nokogiri twitter"
  volumes:
    - ./data:/dashing
