proxy:
  image: georgeyord/reverse-nginx
  ports:
   # Internal port should match PUBLIC_PORT env variable
   - 80:80
   - 443:443
  environment:
   - PUBLIC_PORT=80
    # TARGET_HOST should match linked container internal name
   - TARGET_HOST=target
   - TARGET_PORT=8000
  # Uncomment to activate https, remember to run once: 'docker run proxy' to create the SSL certificates
  #  - SSL_ACTIVE=1
  # Uncomment to activate baic auth
  - HTPASSWD_USER=admin
  - HTPASSWD_PASSWORD=qwerty1
  # Uncomment to change nginx's error level
  # - NGINX_ERROR_LEVEL=warn
  volumes:
   - ./data/ssl:/etc/nginx/ssl
   - ./data/conf.d:/etc/nginx/conf.d/
  links:
   - target:target
target:
 image: jwilder/whoami
