proxy:
  image: georgeyord/reverse-nginx
  ports:
   # Internal port should match PUBLIC_PORT env variable
   - 80:8000
  environment:
   - PUBLIC_PORT=8000
   - TARGET_PORT=8000
  # volumes:
  # Generate a htpasswd and enable the following line to have custom authentication
  #  - data/htpasswd:/etc/nginx/conf.d/htpasswd:ro
  links:
   - target:target
target:
  image: jwilder/whoami