version: "2"
services:
  consul_master:
    extends:
      file: ./services.yml
      service: consul_glitter
    ports:
      - 8400:8400
      - 8500:8500
      - 53:53
    networks:
      - default
      - public
  # consul_master:
  #   extends:
  #     file: ./services.yml
  #     service: consul_progrium
  #   ports:
  #     - 8400:8400
  #     - 8500:8500
  #     - 53:53
  #   networks:
  #     - default
  #     - public
  # consul_1:
  #   extends:
  #     file: ./services.yml
  #     service: consul_1
  # consul_2:
  #   extends:
  #     file: ./services.yml
  #     service: consul_2

  registrator:
    extends:
      file: ./services.yml
      service: registrator
    command: consul://consul_master:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
  # net_tools:
  #   extends:
  #     file: ./services.yml
  #     service: net_tools
  whoami:
    image: jwilder/whoami
    ports:
      - 8001:8000
networks:
  public:
    driver: bridge