ngbp:
  image: nginx:latest
  #ports:
  # - 80:80
  volumes:
  # Change to `data/bin` to check the compiled version of webapp
   - data/build:/usr/local/nginx/html
webhelper:
  image: dockerfile/nodejs-bower-grunt:latest
  volumes:
   - data:/data
