version: '2'
services:
  ipython_notebook:
    extends:
      file: ./services.yml
      service: ipython_notebook
    # ports:
    #   - 8888:8888
    # volumes:
      # Change to the desired directory
      # - data:/notebooks