# REGISTER
registrator:
  image: georgeyord/registrator
  command: etcd://etcd_host:4001/services
  links:
   - etcd:etcd_host
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock

# STORAGE
etcd:
  image: microbox/etcd
  command: -name etcd_host -data-dir /data
  ports:
   - 4001:4001
#   - 7001:7001
etcdinit:

etcdbrowser:
  image: johnmccabe/etcd-browser
  environment:
   - ETCD_HOST=etcd_host
  # - SERVICE_8000_FRONTEND_PORT=80
  # - SERVICE_NAME=etcd.mydocker.co
  links:
   - etcd:etcd_host

# PROXIES
discover:
  image: georgeyord/docker-discover
  net: host
  environment:
   - ETCD_HOST=localhost:4001
   - ADMIN_USER=stats
   - ADMIN_PASSWORD=giguhoko
   - SERVICE_IGNORED=1
  volumes:
   - bin/templates:/app/haproxy/templates
   - data/haproxy/config:/etc/haproxy
   - data/haproxy/log:/var/log/haproxy
  ports:
   - 1936:1936
