version: '2'
services:
  ## DISCOVERY ##
  proxy:
    extends:
      file: ../../compose/nginx/services.yml
      service: nginx
    ports:
      # Internal port should match PUBLIC_PORT env variable
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/ssl:/etc/nginx/ssl:ro
  docker_gen:
    extends:
      file: ../../compose/docker-gen/services.yml
      service: docker_gen
    command: -config /docker-gen/config/discovery.conf
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/docker-gen:/docker-gen
      - ./data/nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
      - proxy
  ## CADVISOR ##
  cadvisor:
    extends:
      file: ../../compose/cadvisor/services.yml
      service: cadvisor
    environment:
      # Used in service discovery
      - SERVICE_NAMES=cadvisor.mydocker.co
      - SERVICE_PORT_MAPPING=443/ssl:8080
  ## IDE ##
  ide:
    extends:
      file: ../../compose/ide/services.yml
      service: ide
    command: --auth ${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD}
    ports:
      - 8181:8181
    environment:
      # Used in service discovery
      - SERVICE_NAME=ide.mydocker.co
      - SERVICE_PORT_MAPPING=443/ssl:8181
    volumes:
      - /root/codebase:/workspace
  ## STATIC SITE ##
  static_mydocker:
    extends:
      file: ../../compose/nginx/services.yml
      service: nginx
    environment:
      # Used in service discovery
      - SERVICE_DEFAULT=true
      - SERVICE_NAME=www.mydocker.co
      - SERVICE_PORT_MAPPING=443/ssl:80
  ## BUTTERFLY ##
  butterfly:
    extends:
      file: ../../compose/web-terminal/services.yml
      service: butterfly
    volumes:
      - ~/.ssh:/root/.ssh:ro
    environment:
      # Used if you have service discovery service
      - PASSWORD=${BASIC_AUTH_PASSWORD}
      # Used in service discovery
      - SERVICE_NAME=terminal.mydocker.co
      - SERVICE_PORT_MAPPING=443/ssl:2233
  ## LOGGER ##
  log_observer:
    extends:
      file: ../../compose/docker-logs/services.yml
      service: log_observer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logio:
    extends:
      file: ../../compose/docker-logs/services.yml
      service: logio
    depends_on:
      - log_observer
    environment:
      # Used if you have service discovery service
      - PASSWORD=${BASIC_AUTH_PASSWORD}
      #
      - SERVICE_NAME=logs.mydocker.co
      - SERVICE_PORT_MAPPING=443/ssl:28778
    ## REGISTRY ##
  # registry_ui:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry_ui
  #   ports:
  #     # To run without SSL encryption
  #     #- 5080:8080
  #     # To enable SSL encryption
  #     - 443:443
  #   # environment:
  #      #
  #      - SERVICE_NAME=registryui.local.mydocker.co
  #      - SERVICE_PORT_MAPPING=443/ssl:8080
  # registry:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry
  #   ports:
  #     - 5000:5000
  #   environment:
  #      #
  #      - SERVICE_NAME=registry.mydocker.co
  #      - SERVICE_PORT_MAPPING=5000:5000
