version: '2'
services:
  ## PROXY ##
  main_proxy:
    extends:
      file: ./services.yml
      service: proxy
    ports:
      # Internal port should match PUBLIC_PORT env variable
      - 80:80
      - 443:443
    environment:
      - PUBLIC_PORT=80
      # Uncomment to activate https, remember to run once: 'docker run proxy' to create the SSL certificates
      - SSL_ACTIVE=1
      # Uncomment to activate wobsocket
      - WEBSOCKER_ACTIVE=1
      # Uncomment to activate basic auth
      - HTPASSWD_USER=${BASIC_AUTH_USER}
      - HTPASSWD_PASSWORD=${BASIC_AUTH_PASSWORD}
  ## CADVISOR ##
  cadvisor:
    extends:
      file: ../../compose/cadvisor/services.yml
      service: cadvisor
    depends_on:
     - main_proxy
    environment:
      # Used in service discovery
      - SERVICE_8080_FRONTEND_PORT=80
      - SERVICE_NAME=cadvisor.mydocker.co
  ## IDE ##
  ide:
    extends:
      file: ../../compose/ide/services.yml
      service: ide
    depends_on:
     - main_proxy
    command: --auth ${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD}
    # ports:
    #   - 8181:8181
    environment:
      # Used in service discovery
      - SERVICE_8181_FRONTEND_PORT=80
      - SERVICE_NAME=ide.mydocker.co
    volumes:
      - /root/codebase:/workspace
  ## STATIC SITE ##
  static_mydocker:
    extends:
      file: ../../compose/nginx/services.yml
      service: nginx
    depends_on:
     - main_proxy
    environment:
      # Used in service discovery
      - SERVICE_80_FRONTEND_PORT=80
      - SERVICE_NAME=www.mydocker.co
  ## BUTTERFLY ##
  butterfly:
    extends:
      file: ../../compose/web-terminal/services.yml
      service: butterfly
    depends_on:
     - main_proxy
    volumes:
      - ~/.ssh:/root/.ssh:ro
    environment:
      # Used if you have serivice discovery service
      - PASSWORD=${BASIC_AUTH_PASSWORD}
      # Used in service discovery
      - SERVICE_2244_FRONTEND_PORT=80
      - SERVICE_NAME=terminal.mydocker.co
  ## LOGGER ##
  log_observer:
    extends:
      file: ../../compose/docker-logs/services.yml
      service: log_observer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logio:
    extends:
      file: ../../compose/docker-logs/services.yml
      service: logio
    depends_on:
      - log_observer
    environment:
      # Used if you have serivice discovery service
      - PASSWORD=${BASIC_AUTH_PASSWORD}
      # Used in service discovery
      - SERVICE_28778_FRONTEND_PORT=80
      - SERVICE_NAME=logs.mydocker.co
    ## REGISTRY ##
  # registry_ui:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry_ui
  #   ports:
  #     # To run without SSL encryption
  #     #- 5080:8080
  #     # To enable SSL encryption
  #     - 443:443
  #   # environment:
  #     # Used in service discovery
  #     - SERVICE_8080_FRONTEND_PORT=80
  #     - SERVICE_NAME=registryui.local.mydocker.co
  # registry:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry
  #   ports:
  #     - 5000:5000
  #   environment:
  #     # Used in service discovery
  #     - SERVICE_5000_FRONTEND_PORT=5000
  #     - SERVICE_NAME=registry.mydocker.co
