version: '2'
services:
  cadvisor:
    extends:
      file: ../../compose/cadvisor/services.yml
      service: cadvisor
    # ports:
    #   - 8080:8080
    environment:
      # Used if you have serivice discovery service
      - SERVICE_8080_FRONTEND_PORT=80
      - SERVICE_NAME=cadvisor.mydocker.co
  ide:
    extends:
      file: ../../compose/ide/services.yml
      service: ide
    command: --auth ${BASIC_AUTH_USER}:${BASIC_AUTH_PASSWORD}
    ports:
      - 8181:8181
    environment:
      # Used in service discovery
      - SERVICE_8181_FRONTEND_PORT=80
      - SERVICE_NAME=ide.mydocker.co
    volumes:
      - /root/codebase:/workspace
  nginx:
    extends:
      file: ../../compose/nginx/services.yml
      service: nginx
    # ports:
    #   - 8088:80
    environment:
      # Used in service discovery
      - SERVICE_80_FRONTEND_PORT=80
      - SERVICE_NAME=nginx.mydocker.co
  # registry_ui:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry_ui
  #   ports:
  #     # To run without SSL encryption
  #     #- 5080:8080
  #     # To enable SSL encryption
  #     - 443:443
  #   # environment:
  #     # Used in service discovery
  #     - SERVICE_8080_FRONTEND_PORT=80
  #     - SERVICE_NAME=registryui.local.mydocker.co
  # registry:
  #   extends:
  #     file: ../../compose/docker-registry/services.yml
  #     service: registry
  #   ports:
  #     - 5000:5000
  #   environment:
  #     # Used in service discovery
  #     - SERVICE_5000_FRONTEND_PORT=5000
  #     - SERVICE_NAME=registry.mydocker.co
