ui:
  image: konradkleine/docker-registry-frontendleine/docker-registry-frontend
  ports:
   #- 5080:8080
   # To enable SSL encryption
   - 443:443
  environment:
   # Used for service discovery
   - SERVICE_8080_FRONTEND_PORT=80
   - SERVICE_NAME=ui.registry.local.mydocker.co
   - ENV_DOCKER_REGISTRY_HOST=registry
   - ENV_DOCKER_REGISTRY_PORT=5000
  volumes:
   - data/h2:/var/lib/h2
   # To enable SSL encryption
   - data/cert/ssl.pem:/etc/apache2/server.crt:ro
   - data/cert/ssl.key:/etc/apache2/server.key:ro
  links:
   - registry:registry
registry:
  image: registry:latest
  ports:
  - 5000:5000
  environment:
   # Used for service discovery
   #- SERVICE_5000_FRONTEND_PORT=5000
   #- SERVICE_NAME=registry.mydocker.co
   - SETTINGS_FLAVOR=local
   - STORAGE_PATH=/opt/registry
   - SEARCH_BACKEND=sqlalchemy
   - SQLALCHEMY_INDEX_DATABASE=sqlite:////sqlite/registry.db
  volumes:
   - data/registry:/opt/registry
   - data/sqlite:/sqlite