app1:
  image:  jwilder/whoami
  ports:
    - 8001:8000
app2:
  image:  jwilder/whoami
  ports:
    - 8002:8000
consul1:
  image: "progrium/consul:latest"
  hostname: "consul1"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "53:53"
  links:
    - app1
  command: "-server -bootstrap-expect 3 -ui-dir /ui"
consul2:
  image: "progrium/consul:latest"
  hostname: "consul2"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - app1
  command: "-server -join consul1"
consul3:
  image: "progrium/consul:latest"
  hostname: "consul3"
  ports:
    - "8400"
    - "8500"
    - "8600"
  links:
    - "consul1:consul1"
    - app1
  command: "-server -join consul1"
