version: "2"
services:
  # REGISTER
  registrator:
    extends:
      file: ./services.yml
      service: registrator
    # entrypoint: bash
    command: etcd://etcd_host:4001/services
    links:
      - etcd:etcd_host

  # STORAGE
  etcd:
    extends:
      file: ./services.yml
      service: etcd
    # ports:
    # - 4001:4001
  #   - 7001:7001
  etcd_init:
    extends:
      file: ./services.yml
      service: etcd_init
  # etcd_init:
  #   extends:
  #     file: ./services.yml
  #     service: etcd_init
  # etcd_proxy:
  #   extends:
  #     file: ./services.yml
  #     service: etcd_proxy
    # environment:
      # Uncomment to activate baic auth
      # - HTPASSWD_USER=${BASIC_AUTH_USER}
      # - HTPASSWD_PASSWORD=${BASIC_AUTH_PASSWORD}
      # Used if you have serivice discovery service
      # - SERVICE_80_FRONTEND_PORT=80
      # - SERVICE_NAME=etcd.mydocker.co
  etcd_ui:
    extends:
      file: ./services.yml
      service: etcd_ui
    environment:
      # Used if you have serivice discovery service
      - SERVICE_8000_FRONTEND_PORT=80
      - SERVICE_NAME=etcd.mydocker.co
    ports:
    - 8000:8000
  # net_tools:
  #   extends:
  #     file: ./services.yml
  #     service: net_tools

  # PROXIES
  discover:
    extends:
      file: ./services.yml
      service: discover
    # network_mode: host
    environment:
    - ADMIN_USER=${BASIC_AUTH_USER}
    - ADMIN_PASSWORD=${BASIC_AUTH_PASSWORD}
    ports:
    - 1936:1936
