version: "2"
services:
  # REGISTER
  registrator:
    extends:
      file: ./docker-compose.yml
      service: registrator
    command: bash -c "go get && go build -ldflags \"-X main.Version dev\" -o /bin/registrator && /bin/registrator etcd://etcd:4001/services"

  # STORAGE
  etcd:
    extends:
      file: ./docker-compose.yml
      service: etcd
    command: -name etcd -data-dir /data
  etcd_init:
    extends:
      file: ./docker-compose.yml
      service: etcd_init
  etcd_ui:
    extends:
      file: ./docker-compose.yml
      service: etcd_ui

  # PROXIES
  discover:
    extends:
      file: ./docker-compose.yml
      service: discover
    # network: host

  # SERVICES
  whoami:
    image: jwilder/whoami
    ports:
     - 8001:8000
  whoareyou:
    image: jwilder/whoami
    ports:
     - 8002:8000
  whoarethey:
    image: jwilder/whoami
    ports:
     - 8003:8000
