nginx:
  image: nginx:latest
  #ports:
  # - 80:80
  #environment:
   # Used for service discovery
   #- SERVICE_80_FRONTEND_PORT=80
   #- SERVICE_NAME=nginx.mydocker.co
  volumes:
   - data:/usr/local/nginx/html
