etcd:
  image: microbox/etcd
  command: -name etcd_host -data-dir /data
  ports:
   - 4001:4001
   - 7001:7001
  volumes:
   - ./data/etcd:/data
etcdinit:
  image: debian
  command: sleep 5; curl -L http://127.0.0.1:4001/v2/keys/backends -XPUT -d dir=true
  links:
   - etcd:etcd_host
register:
  image: jwilder/docker-register
  environment:
   - HOST_IP=188.166.37.31
   - ETCD_HOST=etcd_host:4001
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  links:
   - etcd:etcd_host
discover:
  image: jwilder/docker-discover
  net: host
  environment:
   - ETCD_HOST=localhost:4001
  ports:
   - 1936:1936
browser:
  image: johnmccabe/etcd-browser
  environment:
   - ETCD_HOST=etcd_host
  ports:
   - 8000:8000
  links:
   - etcd:etcd_host
