version: '2'
services:
  butterfly_proxy:
    extends:
      file: ./services.yml
      service: butterfly_proxy
    # ports:
      # Internal port should match PUBLIC_PORT env variable
      # - 80:80
      # - 443:443
    environment:
      - PUBLIC_PORT=80
      # TARGET_HOST should match linked container internal name
      - TARGET_HOST=butterfly
      - TARGET_PORT=2233
      # Uncomment to activate https, remember to run once: 'docker run proxy' to create the SSL certificates
      - SSL_ACTIVE=1
      # Uncomment to activate wobsocket
      - WEBSOCKER_ACTIVE=1
      # Uncomment to activate basic auth
      - HTPASSWD_USER=${BASIC_AUTH_USER}
      - HTPASSWD_PASSWORD=${BASIC_AUTH_PASSWORD}
  butterfly:
    extends:
      file: ./services.yml
      service: butterfly
    depends_on:
     - butterfly_proxy
    # ports:
    #   - 2233:2233
    volumes:
      - ~/.ssh:/root/.ssh:ro
    environment:
      - PASSWORD=${BASIC_AUTH_PASSWORD}
