version: "2"
services:
  butterfly_proxy:
    image: georgeyord/reverse-nginx
    volumes:
     - ./data/ssl:/etc/nginx/ssl
     - ./data/conf.d:/etc/nginx/conf.d/
  butterfly:
    image: "georgeyord/butterfly-web-terminal:latest"