version: "2"
services:
  mysql:
    extends:
      file: ./services.yml
      service: mysql
    volumes:
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty1
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=qwerty1