version: "2"
services:
  mysql:
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql
      - ./log:/var/log/mysql
    #ports:
    # - 3306:3306
    environment:
     # Used in service discovery
     - SERVICE_3306_FRONTEND_PORT=3306
     - SERVICE_NAME=mysql.mydocker.co
     - MYSQL_ROOT_PASSWORD=qwerty1
     - MYSQL_DATABASE=testdb
     - MYSQL_USER=testuser
     - MYSQL_PASSWORD=qwerty1
     # Used in run command
     - MYSQL_PORT_3306_TCP_ADDR=172.17.42.1
     - MYSQL_PORT_3306_TCP_PORT=3306